exclude: 'ciak36.py'
repos:

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.1
    hooks:
      - id: isort

  - repo: https://github.com/python/black
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: local
    hooks:
    - id: create-ciak36
      name: Create ciak36.py
      entry: bash -c 'cd ciak && ./generate_ciak36.sh'
      language: system
      pass_filenames: false
