exclude: 'ciak36.py'
repos:

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/python/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
        args: ["-l", "89"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
    -   id: mypy

  - repo: local
    hooks:
    - id: create-ciak36
      name: Create ciak36.py
      entry: bash -c 'cd ciak && ./generate_ciak36.sh'
      language: system
      pass_filenames: false
